### PR TITLE
Fixes #27 Strategy succeeds even if user is not found

### LINKED ISSUE #27: Strategy succeeds even if user is not found
If a user signs in and the server later removes the user from the database while the JWT is still valid, the strategy will attempt to find the user. If it does not find it, the strategy still succeeds.
~~There is a missing existance check at [verifier.js:30](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L30).~~

~~If there is no user found, the strategy should fail. Likewise, if the user lookup/population fails for another reason, the strategy should *also* fail, as indicated at [verifier.js:36](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L36)~~

*Edit:* The only thing that needs to change is [verifier.js:36](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L36) which should return `done(error)` rather than `done(null, {}, payload)`.

```
feathers-authentication-jwt:verify Looking up user by id 5606d82e-69bc-49fc-8d14-1456a8776ec9 +2ms
feathers-errors NotFound(404): No record found for id '5606d82e-69bc-49fc-8d14-1456a8776ec9' +198ms
feathers-errors {} +1ms
info: error: users - Method: get: No record found for id '5606d82e-69bc-49fc-8d14-1456a8776ec9'
error:  Error
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-errors\lib\index.js:70:27)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Development\FeathersJS\meta-drm\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-rest\lib\wrappers.js:13:23)
feathers-authentication-jwt:verify Error populating user with id 5606d82e-69bc-49fc-8d14-1456a8776ec9 { Error
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-errors\lib\index.js:70:27)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Development\FeathersJS\meta-drm\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-rest\lib\wrappers.js:13:23)
  type: 'FeathersError',
  name: 'NotFound',
  message: 'No record found for id \'5606d82e-69bc-49fc-8d14-1456a8776ec9\'',
  code: 404,
  className: 'not-found',
  data: undefined,
  errors: {} } +6ms
feathers-authentication:passport:authenticate 'jwt' authentication strategy succeeded {} { userId: '5606d82e-69bc-49fc-8d14-1456a8776ec9',
  iat: 1499935648,
  exp: 1500022048,
  aud: 'https://yourdomain.com',
  iss: 'feathers',
  sub: 'anonymous' } +5ms
```
This issue leads to my users still being signed in even after their user is deleted, the only difference is that their `user` object is undefined.

### PR DESCRIPTION
**Pull request by Metamist**
Does this have any side-effects?
OAuth2 authentication package does this already.

### CODE REVIEW

**Comment by Metamist** [comment]
The tests expect the function to not return an error, anyone care to explain why this was the chosen functionality?

**Comment by daffl** [comment]
Some of the tests are failing. I thought there was a reason why it is doing it that way, but @ekryski might know.

**Comment by ekryski** [comment]
@daffl Yes because sometimes you want to just create a JWT without anything in the payload (an anonymous JWT) or you may want to encode everything you need to make authorization decisions into the payload of a JWT that has a shorter TTL (for more scalable apps).

Thanks for the PR @Metamist but I don't think we can merge this. However, I did leave a comment on the issue with a few options for you. https://github.com/feathersjs/feathers-authentication-jwt/issues/27#issuecomment-317565578

**Comment by daffl** [comment]
The problem is that this will return a valid JWT on any error, including database or syntax errors. I'm pretty sure that is the same problem @zusamann is having in his demo application as well.

**Comment by daffl** [comment]
I would think it should only do this on a `NotFound` error.

**Comment by ekryski** [comment]
@daffl Agreed. Which is related to #14. @Metamist if you wanted to update the PR to accommodate that and add a test then we can re-open this PR.

**Comment by zusamann** [comment]
Actually @daffl I don't think I'm having such an error. The custom auth service I've written first finds the user with that username, and only then proceeds, so I'm sure it's not a case of user not being found. Secondly I don't think there are any syntax errors either, the service pretty much works for all cases correctly (correct username/pass, incorrect username/ incorrect pass).

The token seems to be completely valid when returned. And works perfectly fine with the rest client. Only in the websocket client once authenticate call has been made, the rest of the calls fail due to the error `Auth token not found`.

**Comment by zusamann** [comment]
Though in the repository I've shared there is no custom auth service in the latest commits as I was trying to simplify the logic and see if the error still persists, which it does.

**Pull request closed without merging**
